# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: fr

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #Sonata Admins
    admin.web_content:
        class: App\Admin\WebContentAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\WebContent, controller: ~, manager_type: orm, group: admin, label: WebContent }

    admin.user:
        class: App\Admin\UserAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\User, controller: ~, manager_type: orm, group: users, label: Utilisateurs }

    admin.weapon:
        class: App\Admin\WeaponAdmin
        calls:

        tags:
            - { name: sonata.admin, model_class: App\Entity\Weapon, controller: ~, manager_type: orm, group: admin, label: weapon.plural, label_translator_strategy: sonata.admin.label.strategy.noop}

    admin.weapon_category:
        class: App\Admin\WeaponCategoryAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\WeaponCategory, controller: ~, manager_type: orm, group: admin, label: WeaponCategory }

    admin.armor:
        class: App\Admin\ArmorAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Armor, controller: ~, manager_type: orm, group: admin, label: Armor }

    admin.item:
        class: App\Admin\ItemAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Item, controller: ~, manager_type: orm, group: admin, label: Item }

    admin.item_category:
        class: App\Admin\ItemCategoryAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\ItemCategory, controller: ~, manager_type: orm, group: admin, label: ItemCategory }

    admin.material:
        class: App\Admin\MaterialAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Material, controller: ~, manager_type: orm, group: admin, label: Material }

    admin.skill:
        class: App\Admin\SkillAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Skill, controller: ~, manager_type: orm, group: admin, label: Skill }

    admin.stance:
        class: App\Admin\StanceAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Stance, controller: ~, manager_type: orm, group: admin, label: Stance }

    admin.combat_art:
        class: App\Admin\CombatArtAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\CombatArt, controller: ~, manager_type: orm, group: admin, label: CombatArt }

    admin.damage_type:
        class: App\Admin\DamageTypeAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\DamageType, controller: ~, manager_type: orm, group: admin, label: DamageType }

    admin.glossary_trait:
        class: App\Admin\GlossaryTraitAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\GlossaryTrait, controller: ~, manager_type: orm, group: admin, label: GlossaryTrait }

    admin.glossary_condition:
        class: App\Admin\GlossaryConditionAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\GlossaryCondition, controller: ~, manager_type: orm, group: admin, label: GlossaryCondition }

    admin.changelog:
        class: App\Admin\ChangelogAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Changelog, controller: ~, manager_type: orm, group: admin, label: Changelog }

    admin.weapon_property:
        class: App\Admin\WeaponPropertyAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\WeaponProperty, controller: ~, manager_type: orm, group: admin, label: WeaponProperty }

    admin.weapon_property_details:
        class: App\Admin\WeaponPropertyDetailsAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\WeaponPropertyDetails, controller: ~, manager_type: orm, group: admin, label: WeaponPropertyDetails }
