<?php

namespace App\DataFixtures;

use App\Entity\Sort;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class SortFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $sortsData = [
            ['effet' => 'Aspect animal', 'propriete' => NULL, 'ecole' => 'Altération', 'dc' => '4+2X', 'magnitude' => 'Formula 1+1X', 'description' => 'La cible se métamorphose en un animal (catégorie bête ou vermine) Menace [Mag]', 'inkarnai' => 'Kynigi'],
            ['effet' => 'Aisance aquatique', 'propriete' => NULL, 'ecole' => 'Altération', 'dc' => '3+2X', 'magnitude' => 'Time une heure', 'description' => 'La cible obtient le trait Amphibien et peut respirer sous l\'eau pendant [Mag].', 'inkarnai' => 'Nero'],
            ['effet' => 'Marche aquatique', 'propriete' => NULL, 'ecole' => 'Altération', 'dc' => '2+2X', 'magnitude' => 'Time une heure', 'description' => 'La cible peut marcher sur l\'eau comme si elle marchait sur la terre ferme pendant [Mag].', 'inkarnai' => 'Nero'],
            ['effet' => 'Chute ralentie', 'propriete' => 'Réaction', 'ecole' => 'Altération', 'dc' => '3+2X', 'magnitude' => 'Double 5', 'description' => 'La cible ignore les [Mag] premiers mètres de sa prochaine chute lors du calcul des dégâts.', 'inkarnai' => 'Aïgida'],
            ['effet' => 'Lévitation', 'propriete' => 'Concentration, Réaction', 'ecole' => 'Altération', 'dc' => '6+2X', 'magnitude' => 'Double 3', 'description' => 'La cible obtient une vitesse de déplacement en vol de [Mag] mètres par round.', 'inkarnai' => 'Aïgida'],
            ['effet' => 'Saut', 'propriete' => NULL, 'ecole' => 'Altération', 'dc' => '2+2X', 'magnitude' => 'Double 1', 'description' => 'La cible pourra parcourir [Mag] mètre(s)s supplémentaire(s) en hauteur et le double en longueur lors de son prochain saut dans la minute qui suit l\'incantation du sort.', 'inkarnai' => 'Aïgida'],
            ['effet' => 'Verrouillage', 'propriete' => NULL, 'ecole' => 'Altération', 'dc' => '3+3X', 'magnitude' => 'Double 5', 'description' => 'La serrure ciblé devient verrouillée. Ouvrir cette serrure nécessite un test étendu de crochetage avec un DR total de [Mag].', 'inkarnai' => 'Ourgal'],
            ['effet' => 'Déverrouillage', 'propriete' => NULL, 'ecole' => 'Altération', 'dc' => '3+3X', 'magnitude' => 'Double 5', 'description' => 'La serrure ciblé ajoute [Mag] DR au total nécessaire à la déverrouiller.', 'inkarnai' => 'Ourgal'],
            ['effet' => 'Transmutation', 'propriete' => NULL, 'ecole' => 'Altération', 'dc' => '10+1X', 'magnitude' => 'Dice_nb 2d4', 'description' => 'Le lanceur lance [Mag] et en fait le total, si le résultat dépasse la résistance magique de la cible, elle devient métallique ou minérale. Une cible métamorphosée en pierre ou en métal est invulnérable aux dégâts du temps et son poids est multiplié par 5. L\'effet dure indéfiniment tant que la cible ne brise pas le sort.<br/>Pour se libérer, la cible peut effectuer chaque jour un jet d\'Altération(Volonté ou Vigueur) avec un DC équivalent au résultat du lanceur. Le Nombre de DR (NDR) qu\'il doit rassembler pour se libérer équivaut à la somme des d4 lancés initialement par le lanceur.', 'inkarnai' => 'Ourgal'],
            ['effet' => 'Renforcement [Caractéristique]', 'propriete' => '[Force, Dextérité, Agilité, Vigueur, Intelligence, Volonté, Perception, Éloquence]', 'ecole' => 'Altération', 'dc' => '4+3X', 'magnitude' => 'Formula 1+1X', 'description' => 'La cible voit sa [Caractéristique] augmenter de [Mag] cran(s) pendant une minute.', 'inkarnai' => 'Agones, Eftis, Orizo, Kynigi, Psema'],
            ['effet' => 'Affaiblissement [Caractéristique]', 'propriete' => '[Force, Dextérité, Agilité, Vigueur, Intelligence, Volonté, Perception, Éloquence]', 'ecole' => 'Altération', 'dc' => '4+3X', 'magnitude' => 'Formula 1+1X', 'description' => 'La [Caractéristique] de la cible diminue de [Mag] crans pendant une minute.<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur dans le cas d\'une caractéristique physique ou de Volonté pour une caractéristique mentale avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu\'il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.', 'inkarnai' => 'Agones, Eftis, Orizo, Kynigi, Psema'],
            ['effet' => 'Résistance [Élément]', 'propriete' => '[Acide, Eau, Feu, Foudre, Glace, Lumière, Nécrotique, Poison]', 'ecole' => 'Altération', 'dc' => '3+2X', 'magnitude' => 'Formula 1+1X', 'description' => 'Procure à la cible le trait Résistance([Mag],[élément]).', 'inkarnai' => 'Aïgida, Anathos, Horoï, Kuga, Nero, Safi'],
            ['effet' => 'Vulnérabilité [Élément]', 'propriete' => 'Concentration, [Acide, Eau, Feu, Foudre, Glace, Lumière, Nécrotique, Poison]', 'ecole' => 'Altération', 'dc' => '3+2X', 'magnitude' => 'Formula 1+1X', 'description' => 'La cible subit le trait Vulnérabilité([Mag],[élément]).<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu\'il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.', 'inkarnai' => 'Aïgida, Anathos, Horoï, Kuga, Nero, Safi'],
            ['effet' => 'Guérison', 'propriete' => NULL, 'ecole' => 'Altération', 'dc' => '4', 'magnitude' => '-', 'description' => 'La cible passe un test de Vigueur avec un DC équivalent au triple de ses blessures et un bonus équivalent au DR du lanceur. Sur une réussite, la cible guérie d\'une blessure. Chaque palier de 3 DR de la cible soigne une blessure supplémentaire.', 'inkarnai' => 'Agapi'],
            ['effet' => 'Stabilisation', 'propriete' => NULL, 'ecole' => 'Altération', 'dc' => '4', 'magnitude' => '-', 'description' => 'La cible passe un test de Vigueur avec un DC équivalent au triple de ses blessures et un bonus équivalent au DR du lanceur. Sur une réussite, la cible n\'est plus mourante et devient stable.', 'inkarnai' => 'Agapi'],
            ['effet' => 'Récupération', 'propriete' => NULL, 'ecole' => 'Altération', 'dc' => '2', 'magnitude' => '-', 'description' => 'La cible passe un test de Vigueur pour les traumas Physiques ou de Volonté pour les traumas Mentaux avec un DC équivalent au triple de ses traumas physiques/mentuax et un bonus équivalent au DR du lanceur. Sur une réussite, la cible guérie d\'un trauma. Chaque palier de 3 DR de la cible soigne un trauma supplémentaire.', 'inkarnai' => 'Agapi'],
            ['effet' => 'Purge', 'propriete' => 'Concentration', 'ecole' => 'Altération', 'dc' => '3+2X', 'magnitude' => 'AD +1', 'description' => 'La cible obtient [Mag] avantages pour résister et purger les effets négatifs(Vulnérabilité, Saignement, Poison, etc..) tant que le lanceur se concentre sur le sort.', 'inkarnai' => 'Agapi'],
            ['effet' => 'Invisibilité', 'propriete' => 'Concentration', 'ecole' => 'Altération', 'dc' => '8', 'magnitude' => '-', 'description' => 'La cible devient invisible et le reste tant que le lanceur se concentre sur le sort.', 'inkarnai' => 'Safi'],
            ['effet' => 'Armure', 'propriete' => '[Physique, Magique]', 'ecole' => 'Conjuration', 'dc' => '4+3X', 'magnitude' => 'Formula 1+1X', 'description' => 'La résistance [type] de la cible augmente de [Mag].', 'inkarnai' => 'Pravoï'],
            ['effet' => 'Protection', 'propriete' => 'Réaction', 'ecole' => 'Conjuration', 'dc' => '3+3X', 'magnitude' => 'Double 2', 'description' => 'Réduis les dégâts subis par la cible de [Mag] pour une instance de dégâts dans la minute qui suit l\'incantation du sort.', 'inkarnai' => 'Pravoï'],
            ['effet' => 'Entrave', 'propriete' => 'Concentration', 'ecole' => 'Conjuration', 'dc' => '4+2X', 'magnitude' => 'AD -0', 'description' => 'La cible est immobilisée.<br/>Pour se libérer, la cible peut effectuer chaque round un test de Force, de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu\'il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.', 'inkarnai' => 'Pravoï'],
            ['effet' => 'Toile d\'araignée', 'propriete' => NULL, 'ecole' => 'Conjuration', 'dc' => '3+3X', 'magnitude' => 'Double 2', 'description' => 'L\'endroit ciblé par le lanceur diminue la vitesse des entité le traversant de [Mag].', 'inkarnai' => 'Kynigi'],
            ['effet' => 'Invocation de Karnarim élémentaire', 'propriete' => '[Acide, Eau, Feu, Foudre, Glace, Lumière, Métal, Nécrotique, Pierre, Poison, Sable, Terre]', 'ecole' => 'Conjuration', 'dc' => '6', 'magnitude' => '-', 'description' => 'Invoque un Karnarim de l\'[élément] pendant une minute. Voir Élémentaire mineur dans le Bestiaire.', 'inkarnai' => 'Aïgida, Anathos, Horoï, Kormo, Kuga, Nero, Ourgal, Safi'],
            ['effet' => 'Invocation d\'Arme', 'propriete' => NULL, 'ecole' => 'Conjuration', 'dc' => '6+2X', 'magnitude' => 'Dice_scale 1d4', 'description' => 'Invoque une arme infligeant [Mag] dégâts magiques à l\'endroit ciblé, cette arme peut utiliser la caractéristique de Volonté du lanceur pour les jets de Style de Combat.', 'inkarnai' => 'Agones'],
            ['effet' => 'Projection psychique', 'propriete' => 'Concentration', 'ecole' => 'Conjuration', 'dc' => '10', 'magnitude' => '-', 'description' => 'L\'esprit de cible est envoyé dans un domaine de Karnaï.<br/>Sans esprit pour le contrôler, le corps de la cible est inanimé pendant cette période. Une minute dans le monde matériel équivaut à une heure dans le monde de Karnaï.<br/>L\'esprit de la cible doit consentir à ce voyage ou au moins ne pas y être opposée sinon le lanceur risque de perdre son propre esprit lors de l\'incantation.', 'inkarnai' => 'Selon le domaine visité'],
            ['effet' => 'Bannissement', 'propriete' => NULL, 'ecole' => 'Conjuration', 'dc' => '0', 'magnitude' => '-', 'description' => 'La cible est renvoyé dans sa dimension d\'Origine.<br/>Elle doit passer un test de Vigueur ou Volonté opposé à l\'incantation du lanceur si elle souhaite résister.<br/>Si l\'invocateur de la cible est conscient de la tentative de bannissement, il peut effectuer le test à la place de la cible en utilisant sa compétence de Conjuration.', 'inkarnai' => 'Pravoï'],
            ['effet' => 'Pas de l\'ombre', 'propriete' => NULL, 'ecole' => 'Conjuration', 'dc' => '6+2X', 'magnitude' => 'Distance 10 mètres', 'description' => 'La cible doit se tenir dans une ombre. Elle se téléporte dans une autre ombre située à moins de [Mag] de sa position. Si elle souhaite résister, elle doit passer un test de Volonté avec un DC équivalent au résultat du lanceur.', 'inkarnai' => 'Eftis'],
            ['effet' => 'Téléportation', 'propriete' => NULL, 'ecole' => 'Conjuration', 'dc' => '8', 'magnitude' => 'Distance 10 mètres', 'description' => 'La cible se téléporte sur une distance de [Mag] ou moins dans un éclair de lumière. Si elle souhaite résister, elle doit passer un test de Volonté avec un DC équivalent au résultat du lanceur.', 'inkarnai' => 'Safi'],
            ['effet' => 'Racines du monde', 'propriete' => NULL, 'ecole' => 'Conjuration', 'dc' => '6', 'magnitude' => 'Distance 10 mètres', 'description' => 'La cible se téléporte via les racines d\'un arbre sur une distance de [Mag] ou moins, elle doit être en contact avec un arbre en vie et réapparaître sur un autre arbre en vie. Si elle souhaite résister, elle doit passer un test de Volonté avec un DC équivalent au résultat du lanceur.', 'inkarnai' => 'Kormo'],
            ['effet' => 'Assaut minéral', 'propriete' => '[Métal, Pierre, Terre, Sable]', 'ecole' => 'Conjuration', 'dc' => '2+2X', 'magnitude' => 'Dice_scale d2', 'description' => 'La cible subit [Mag] dégâts physiques.', 'inkarnai' => 'Kormo, Ourgal'],
            ['effet' => 'Assaut élémentaire', 'propriete' => '[Acide, Eau, Feu, Foudre, Glace, Lumière, Nécrotique, Poison]', 'ecole' => 'Conjuration', 'dc' => '2+2X', 'magnitude' => 'Dice_scale d2', 'description' => 'La cible subit [Mag] dégâts d\'[Élément].', 'inkarnai' => 'Aïgida, Anathos, Horoï, Kuga, Nero, Safi'],
            ['effet' => 'Réanimation', 'propriete' => NULL, 'ecole' => 'Domination', 'dc' => '6+2X', 'magnitude' => 'Gabarit P && Time une heure', 'description' => 'La cible doit être une créature inanimé de gabarit [Mag] ou moins pendant [Mag]. La créature réanimé agit comme bon lui semble.', 'inkarnai' => 'Anathos'],
            ['effet' => 'Contrôle mental', 'propriete' => 'Concentration', 'ecole' => 'Domination', 'dc' => '6', 'magnitude' => '-', 'description' => 'La cible passe sous le contrôle du lanceur.<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu\'il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.', 'inkarnai' => 'Kynigi, Kormo, Psema'],
            ['effet' => 'Réécriture mémorielle', 'propriete' => NULL, 'ecole' => 'Domination', 'dc' => '8', 'magnitude' => '-', 'description' => 'La dernière minute de mémoire de la cible est modifiée par le lanceur.<br/>Pour résister, la cible peut passer un test de Vigueur ou de Volonté avec un DC équivalent au résultat du lanceur.<br/>Si la modification porte sur une période minoritaire de la vie de la cible et qu\'elle est incohérente ou trop contradictoire avec le comportement habituel de la cible, elle considérera les effets du sort comme une hallucination/mauvais rêve. Dans le cas d\'une modification de grande ampleur (au moins la moitié de la vie de la cible), seules les pensés incohérentes sont perçues comme des mauvais rêves.', 'inkarnai' => 'Psema'],
            ['effet' => 'Mot de pouvoir : Douleur', 'propriete' => 'Concentration', 'ecole' => 'Domination', 'dc' => '4+2X', 'magnitude' => 'Double 1 && AD -1', 'description' => 'La cible voie sa vitesse diminuée de [Mag] et effectue toute action (sauf se libérer) avec [Mag] désavantage(s).<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu\'il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.', 'inkarnai' => 'Psema'],
            ['effet' => 'Mot de pouvoir : Mort', 'propriete' => NULL, 'ecole' => 'Domination', 'dc' => '15', 'magnitude' => '-', 'description' => 'La cible meurt instantanément.<br/>Pour résister, la cible peut lancer son dé de Vigueur et son dé de Volonté, en faire la somme et la comparer au résultat du lanceur.', 'inkarnai' => 'Anathos'],
            ['effet' => 'Télékinésie', 'propriete' => 'Concentration', 'ecole' => 'Domination', 'dc' => '2+2X', 'magnitude' => 'Formula 1+1X', 'description' => 'La cible obtient le trait Télékinésiste([Mag]).', 'inkarnai' => 'Agones'],
            ['effet' => 'Peur', 'propriete' => NULL, 'ecole' => 'Domination', 'dc' => '5', 'magnitude' => '1 minute', 'description' => 'La cible est Effrayé(lanceur).<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu\'il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.', 'inkarnai' => 'Agapi, Psema'],
            ['effet' => 'Calme', 'propriete' => NULL, 'ecole' => 'Domination', 'dc' => '5', 'magnitude' => '1 minute', 'description' => 'La cible est fasciné.<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu\'il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.', 'inkarnai' => 'Psema'],
            ['effet' => 'Rage', 'propriete' => NULL, 'ecole' => 'Domination', 'dc' => '5', 'magnitude' => '1 minute', 'description' => 'La cible considère tout le monde comme un adversaire.<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu\'il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.', 'inkarnai' => 'Agones'],
            ['effet' => 'Silence', 'propriete' => NULL, 'ecole' => 'Domination', 'dc' => '5', 'magnitude' => '1 minute', 'description' => 'La cible est incapable de parler.<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu\'il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.', 'inkarnai' => 'Psema'],
            ['effet' => 'Apparence trompeuse', 'propriete' => 'Concentration', 'ecole' => 'Domination', 'dc' => '6', 'magnitude' => '-', 'description' => 'La cible est perçue comme quelqu\'un d\'autre.<br/>Se rendre compte du sort nécessite de passer un test d\'Observation(Per) ou d\'Arcanes(Int ou Per) avec un DC équivalent au résultat du lanceur de sort.', 'inkarnai' => 'Psema'],
            ['effet' => 'Télépathie', 'propriete' => 'Concentration', 'ecole' => 'Mysticisme', 'dc' => '2', 'magnitude' => '-', 'description' => 'La cible obtient le trait Télépathe.', 'inkarnai' => 'Orizo'],
            ['effet' => 'Archives d\'Orizo', 'propriete' => NULL, 'ecole' => 'Mysticisme', 'dc' => '2+2X', 'magnitude' => 'AD +1', 'description' => 'Le prochain test de compétence de la cible pouvant être facilité avec des connaissances spécifiques se fera avec [Mag] avantage(s).', 'inkarnai' => 'Orizo'],
            ['effet' => 'Détection de la vie / des morts / de la magie', 'propriete' => NULL, 'ecole' => 'Mysticisme', 'dc' => '3+1X', 'magnitude' => 'Double 10', 'description' => 'Détecte les être vivants / les morts / la magie dans un rayon de [Mag] mètres du point d\'impact du sort.', 'inkarnai' => 'Kynigi, Anathos, Orizo'],
            ['effet' => 'Vision véritable', 'propriete' => 'Concentration', 'ecole' => 'Mysticisme', 'dc' => '6', 'magnitude' => '-', 'description' => 'La cible voit tout, même les entités invisibles, peut voir dans le noir le plus complet et même dans une obscurité magique.<br/>La cible peut voir grâce à ce sort même si elle est aveugle.', 'inkarnai' => 'Orizo'],
            ['effet' => 'Destinée', 'propriete' => NULL, 'ecole' => 'Mysticisme', 'dc' => '6+2X', 'magnitude' => 'Dice_nb 2d6', 'description' => 'Le lanceur peut ajouter/enlever le résultat d\'un des dés lancés par ce sort pour modifier le résultat de n\'importe quel test. (Le lanceur doit annoncer l\'utilisation d\'un dé pré-tiré avant que le dé ne soit lancé).', 'inkarnai' => 'Tychi'],
            ['effet' => 'Augure', 'propriete' => NULL, 'ecole' => 'Mysticisme', 'dc' => '5', 'magnitude' => '-', 'description' => 'La cible est avertie de son futur proche. (fortune, péril, les deux ou rien).', 'inkarnai' => 'Tychi'],
            ['effet' => 'Prophétie', 'propriete' => NULL, 'ecole' => 'Mysticisme', 'dc' => '10', 'magnitude' => '-', 'description' => 'La cible obtient une réponse fiable sur un évènement à venir dans les 7 jours. (avoir recours à cet effet sans 7 jours d\'intervalles augmente de 25% les chances de réponse aléatoires).', 'inkarnai' => 'Tychi'],
            ['effet' => 'Communion avec la nature', 'propriete' => NULL, 'ecole' => 'Mysticisme', 'dc' => '6', 'magnitude' => '-', 'description' => 'La cible obtient trois informations sur son environnement.', 'inkarnai' => 'Kormo et Kynigi'],
            ['effet' => 'Localisation d\'entité', 'propriete' => 'Concentration', 'ecole' => 'Mysticisme', 'dc' => '4+2X', 'magnitude' => 'Distance 100 mètres', 'description' => 'La cible connait la position de l\'entité de son choix dans un rayon de [Mag].', 'inkarnai' => 'Kynigi'],
            ['effet' => 'Langue enchantée', 'propriete' => 'Concentration', 'ecole' => 'Mysticisme', 'dc' => '4', 'magnitude' => '-', 'description' => 'La cible sait parler dans toute les langues tant que le lanceur se concentre sur le sort.', 'inkarnai' => 'Orizo'],
            ['effet' => 'Lien sensoriel', 'propriete' => 'Concentration', 'ecole' => 'Mysticisme', 'dc' => '6+2X', 'magnitude' => 'Distance 100 mètres', 'description' => 'La cible peut voir/entendre/sentir à travers les sens d\'une créature consentante dans un rayon de [Mag].', 'inkarnai' => 'Kynigi'],
            ['effet' => 'Création élémentaire', 'propriete' => '[Glace, Métal, Pierre, Sable, Terre]', 'ecole' => 'Conjuration', 'dc' => '2+2X', 'magnitude' => 'Double 10 && Time une minute', 'description' => 'L\'[élément] apparaît à l\'endroit ciblé pendant [Mag]. La création doit subir [Mag] dégâts avant de se briser.', 'inkarnai' => 'Kormo, Nero, Ourgal'],
            ['effet' => 'Bourrasque', 'propriete' => 'Concentration', 'ecole' => 'Conjuration', 'dc' => '2+2X', 'magnitude' => 'Double 10', 'description' => 'Invoque du vent se déplaçant à [Mag] km/h à l\'endroit ciblé, la direction du vent est au choix du lanceur.', 'inkarnai' => 'Aïgida'],
            ['effet' => 'Spores [type]', 'propriete' => '[Paralysie, Sommeil, Fascination, Confusion,...]', 'ecole' => 'Conjuration', 'dc' => '5', 'magnitude' => '-', 'description' => 'Invoque des spores infligeant l\'effet [type].<br/>Pour se libérer, la cible peut effectuer un test de Force, de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu\'il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.<br/>La fréquence du test dépend du [type] :Paralysie/Fascination/Confusion -> chaque round ; sommeil chaque minute', 'inkarnai' => 'Kormo'],
            ['effet' => 'Contrôle de la température', 'propriete' => 'Concentration', 'ecole' => 'Conjuration', 'dc' => '2+3X', 'magnitude' => 'Double 5', 'description' => 'Augmente ou diminue la température ambiante de la cible de [Mag] C°.', 'inkarnai' => 'Horoï'],
            ['effet' => 'Lumière', 'propriete' => NULL, 'ecole' => 'Conjuration', 'dc' => '2+2X', 'magnitude' => 'Double 5 && Time une heure', 'description' => 'Génère de la lumière vive sur [Mag] mètres et de la lumière faible sur [Mag]*2 mètres de façon circulaire pendant [Mag].', 'inkarnai' => 'Safi'],
            ['effet' => 'Création illusoire', 'propriete' => NULL, 'ecole' => 'Conjuration', 'dc' => '3+2', 'magnitude' => 'Gabarit TP && Time une minute', 'description' => 'Façonne une création intangible de la forme souhaitée avec sons et odeurs de gabarit [Mag] ou moins pendant [Mag] minute. Un test d\'Observation ou d\'Investigation avec un DC équivalent au résultat du lanceur est nécessaire pour se rendre compte de l\'illusion sans la toucher.', 'inkarnai' => 'Psema'],
        ];

        foreach ($sortsData as $data) {
            $sort = new Sort();
            $sort->setEffet($data['effet']);
            $sort->setPropriete($data['propriete']);
            $sort->setEcole($data['ecole']);
            $sort->setDc($data['dc']);
            $sort->setMagnitude($data['magnitude']);
            $sort->setDescription($data['description']);
            $sort->setInkarnai($data['inkarnai']);
            $manager->persist($sort);
        }

        $manager->flush();
    }
}