<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260805000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore full sort descriptions truncated during import (content lost after CRLF)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("UPDATE \"sort\" SET description = 'Le lanceur lance [Mag] et en fait le total, si le résultat dépasse la résistance magique de la cible, elle devient métallique ou minérale. Une cible métamorphosée en pierre ou en métal est invulnérable aux dégâts du temps et son poids est multiplié par 5. L''effet dure indéfiniment tant que la cible ne brise pas le sort.<br/>Pour se libérer, la cible peut effectuer chaque jour un jet d''Altération(Volonté ou Vigueur) avec un DC équivalent au résultat du lanceur. Le Nombre de DR (NDR) qu''il doit rassembler pour se libérer équivaut à la somme des d4 lancés initialement par le lanceur.' WHERE effet = 'Transmutation'");
        $this->addSql("UPDATE \"sort\" SET description = 'La [Caractéristique] de la cible diminue de [Mag] crans pendant une minute.<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur dans le cas d''une caractéristique physique ou de Volonté pour une caractéristique mentale avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu''il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.' WHERE effet = 'Affaiblissement [Caractéristique]'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible subit le trait Vulnérabilité([Mag],[élément]).<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu''il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.' WHERE effet = 'Vulnérabilité [Élément]'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible passe un test de Vigueur avec un DC équivalent au triple de ses blessures et un bonus équivalent au DR du lanceur. Sur une réussite, la cible guérie d''une blessure. Chaque palier de 3 DR de la cible soigne une blessure supplémentaire.' WHERE effet = 'Guérison'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible passe un test de Vigueur pour les traumas Physiques ou de Volonté pour les traumas Mentaux avec un DC équivalent au triple de ses traumas physiques/mentuax et un bonus équivalent au DR du lanceur. Sur une réussite, la cible guérie d''un trauma. Chaque palier de 3 DR de la cible soigne un trauma supplémentaire.' WHERE effet = 'Récupération'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible est immobilisée.<br/>Pour se libérer, la cible peut effectuer chaque round un test de Force, de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu''il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.' WHERE effet = 'Entrave'");
        $this->addSql("UPDATE \"sort\" SET description = 'Invoque un Karnarim de l''[élément] pendant une minute. Voir Élémentaire mineur dans le Bestiaire.' WHERE effet = 'Invocation de Karnarim élémentaire'");
        $this->addSql("UPDATE \"sort\" SET description = 'Invoque une arme infligeant [Mag] dégâts magiques à l''endroit ciblé, cette arme peut utiliser la caractéristique de Volonté du lanceur pour les jets de Style de Combat.' WHERE effet = 'Invocation d''Arme'");
        $this->addSql("UPDATE \"sort\" SET description = 'L''esprit de cible est envoyé dans un domaine de Karnaï.<br/>Sans esprit pour le contrôler, le corps de la cible est inanimé pendant cette période. Une minute dans le monde matériel équivaut à une heure dans le monde de Karnaï.<br/>L''esprit de la cible doit consentir à ce voyage ou au moins ne pas y être opposée sinon le lanceur risque de perdre son propre esprit lors de l''incantation.' WHERE effet = 'Projection psychique'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible est renvoyé dans sa dimension d''Origine.<br/>Elle doit passer un test de Vigueur ou Volonté opposé à l''incantation du lanceur si elle souhaite résister.<br/>Si l''invocateur de la cible est conscient de la tentative de bannissement, il peut effectuer le test à la place de la cible en utilisant sa compétence de Conjuration.' WHERE effet = 'Bannissement'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible doit se tenir dans une ombre. Elle se téléporte dans une autre ombre située à moins de [Mag] de sa position. Si elle souhaite résister, elle doit passer un test de Volonté avec un DC équivalent au résultat du lanceur.' WHERE effet = 'Pas de l''ombre'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible se téléporte sur une distance de [Mag] ou moins dans un éclair de lumière. Si elle souhaite résister, elle doit passer un test de Volonté avec un DC équivalent au résultat du lanceur.' WHERE effet = 'Téléportation'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible se téléporte via les racines d''un arbre sur une distance de [Mag] ou moins, elle doit être en contact avec un arbre en vie et réapparaître sur un autre arbre en vie. Si elle souhaite résister, elle doit passer un test de Volonté avec un DC équivalent au résultat du lanceur.' WHERE effet = 'Racines du monde'");
        $this->addSql("UPDATE \"sort\" SET description = 'Invoque du vent se déplaçant à [Mag] km/h à l''endroit ciblé, la direction du vent est au choix du lanceur.' WHERE effet = 'Bourrasque'");
        $this->addSql("UPDATE \"sort\" SET description = 'Invoque des spores infligeant l''effet [type].<br/>Pour se libérer, la cible peut effectuer un test de Force, de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu''il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.<br/>La fréquence du test dépend du [type] :Paralysie/Fascination/Confusion -> chaque round ; sommeil chaque minute' WHERE effet = 'Spores [type]'");
        $this->addSql("UPDATE \"sort\" SET description = 'Façonne une création intangible de la forme souhaitée avec sons et odeurs de gabarit [Mag] ou moins pendant [Mag] minute. Un test d''Observation ou d''Investigation avec un DC équivalent au résultat du lanceur est nécessaire pour se rendre compte de l''illusion sans la toucher.' WHERE effet = 'Création illusoire'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible passe sous le contrôle du lanceur.<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu''il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.' WHERE effet = 'Contrôle mental'");
        $this->addSql("UPDATE \"sort\" SET description = 'La dernière minute de mémoire de la cible est modifiée par le lanceur.<br/>Pour résister, la cible peut passer un test de Vigueur ou de Volonté avec un DC équivalent au résultat du lanceur.<br/>Si la modification porte sur une période minoritaire de la vie de la cible et qu''elle est incohérente ou trop contradictoire avec le comportement habituel de la cible, elle considérera les effets du sort comme une hallucination/mauvais rêve. Dans le cas d''une modification de grande ampleur (au moins la moitié de la vie de la cible), seules les pensés incohérentes sont perçues comme des mauvais rêves.' WHERE effet = 'Réécriture mémorielle'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible voie sa vitesse diminuée de [Mag] et effectue toute action (sauf se libérer) avec [Mag] désavantage(s).<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu''il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.' WHERE effet = 'Mot de pouvoir : Douleur'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible meurt instantanément.<br/>Pour résister, la cible peut lancer son dé de Vigueur et son dé de Volonté, en faire la somme et la comparer au résultat du lanceur.' WHERE effet = 'Mot de pouvoir : Mort'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible est Effrayé(lanceur).<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu''il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.' WHERE effet = 'Peur'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible est fasciné.<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu''il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.' WHERE effet = 'Calme'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible considère tout le monde comme un adversaire.<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu''il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.' WHERE effet = 'Rage'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible est incapable de parler.<br/>Pour se libérer, la cible peut effectuer chaque round un test de Vigueur ou de Volonté avec un DC équivalent au cercle du sort. Le Nombre de DR (NDR) qu''il doit rassembler pour se libérer équivaut au résultat du lanceur de sort.' WHERE effet = 'Silence'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible est perçue comme quelqu''un d''autre.<br/>Se rendre compte du sort nécessite de passer un test d''Observation(Per) ou d''Arcanes(Int ou Per) avec un DC équivalent au résultat du lanceur de sort.' WHERE effet = 'Apparence trompeuse'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible voit tout, même les entités invisibles, peut voir dans le noir le plus complet et même dans une obscurité magique.<br/>La cible peut voir grâce à ce sort même si elle est aveugle.' WHERE effet = 'Vision véritable'");
        $this->addSql("UPDATE \"sort\" SET description = 'Le lanceur peut ajouter/enlever le résultat d''un des dés lancés par ce sort pour modifier le résultat de n''importe quel test. (Le lanceur doit annoncer l''utilisation d''un dé pré-tiré avant que le dé ne soit lancé).' WHERE effet = 'Destinée'");
        $this->addSql("UPDATE \"sort\" SET description = 'La cible obtient une réponse fiable sur un évènement à venir dans les 7 jours. (avoir recours à cet effet sans 7 jours d''intervalles augmente de 25% les chances de réponse aléatoires).' WHERE effet = 'Prophétie'");
    }

    public function down(Schema $schema): void
    {
    }
}
