<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260724000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Insert the 37 original combat_art entries (from MySQL dump) with section/category/tier/critique data';
    }

    public function up(Schema $schema): void
    {
        // Section 1: Basics (13 entries)
        $this->addSql("INSERT INTO combat_art (name, description, conditions, effect, cost, assaillant_test, defender_test, category, tier, critique, order_index, section) VALUES
            ('Balayette', 'Le héros tente de faire tomber son adversaire au sol', NULL, 'La cible est au sol et passe son prochain tour, elle subit 2 dégâts', NULL, 'Action bonus : DEX', 'AGI', NULL, NULL, 'R: La cible s''assome et sombre dans l''inconscience<br/>E: Le héros chute et passe son prochain tour', 1, 1),
            ('Charge d''épaule', 'Le héros bouscule son adversaire pour le faire tomber au sol', NULL, 'La cible est au sol et passe son prochain tour, elle subit 4 dégâts', NULL, 'Action bonus : FOR', 'VIG', NULL, NULL, 'R: La cible s''assome et sombre dans l''inconscience<br/>E: Le héros trébuche et passe son prochain tour', 2, 1),
            ('Coup dans les yeux', 'Avec un rapide coup de dague au visage, le héros aveugle momentanément son adversaire', 'Dague<br/>Cible sans casque', 'cible aveuglée partiellement : Atq et Prd -20 (3 tours)', NULL, 'Action simple :<br/>Jet d''Atq à -20', 'Parade/Esquive à +10', NULL, NULL, 'R: Dégâts + 2, cible aveugle 5 tours<br/>E: /', 3, 1),
            ('Désarmement', 'Le héros lutte habilement pour ôter son arme à son adversaire', 'Après une attaque réussie', 'La cible est désarmée', NULL, 'Action bonus : DEX ou FOR', 'DEX', NULL, NULL, 'R: /<br/>E: Le héros fait tomber son arme à ses pieds.', 4, 1),
            ('Feinte', 'Le héros distrait son adversaire avant de frapper. La forme de la feinte est à préciser par le joueur', 'Arme de corps-à-corps pouvant infliger des dégâts perforants', 'R: dégâts + 4<br/>E: Le héros baisse sa garde et subit une attaque d''opportunité', NULL, 'Action bonus :<br/>Le joueur lance un d100 avant de faire son jet d''attaque (avec bonus éventuels selon le personnage et au choix du MJ), son adversaire lance aussi un d100 (encore bonus et malus au choix du MJ). Le plus haut score l''emporte.', 'La cible ne peut pas se défendre', NULL, NULL, 'R: dégâts + 4<br/>E: Le héros baisse sa garde et subit une attaque d''opportunité', 5, 1),
            ('Fente', 'Le héros s''appuie sur sa jambe avant pour frapper de loin', 'Arme de corps-à-corps pouvant infliger des dégâts perforants', 'La portée augmente d''un mètre', NULL, 'Action simple :<br/>Moyenne Atq/AGI', 'Parade/Esquive classique', NULL, NULL, 'R: /<br/>E: Le héros trébuche et tombe au sol', 6, 1),
            ('Lacération', 'Le héros frappe pour ouvrir les veines de son adversaire', 'Cible sans armure à l''endroit ciblé', 'la cible saigne (1d6/tour) pendant 3 tours', NULL, 'Action simple :<br/>Jet d''Atq à -10, les dégâts sont divisés par deux', 'Parade/Esquive classique, si le coup touche, épreuve de VIG pour contrer le saignement', NULL, NULL, 'R: 5 tours de saignement<br/>E: /', 7, 1),
            ('Lutte', 'Le héros agrippe son adversaire pour entraver ses options de combat', 'Une main libre (si deux mains libres bonus de +20)', 'Le héros doit réussir un jet par tour pour maintenir sa prise (FOR ou DEX du héros - FOR ou DEX de cible + 5 par tour). Durant la lutte, le héros peut déplacer la cible de la moitié de sa vitesse de déplacement, l''attaquer (ignore l''armure à 30 ou moins), l''immobiliser ou l''attacher (avec cordes ou autre) via une épreuve de DEX à -30.', NULL, 'Action simple : DEX ou FOR', 'DEX ou FOR pour contrer la prise', NULL, NULL, NULL, 8, 1),
            ('Provocation', 'Le héros provoque son/ses adversaire(s) et le(s) pousse(nt) à l''attaquer en priorité', NULL, 'La cible se concentre sur le héros et attaque désormais avec deux désavantages les autres cibles pendant 3 rounds', NULL, 'Action bonus : ELO', 'Un jet de VOL pour chaque adversaire provoqué', NULL, NULL, 'R: La durée de provocation passe à 5 rounds, la cible ne frappe que le héros<br/>E: Le héros baisse sa garde et subit une attaque d''opportunité', 9, 1),
            ('Ralliement', 'Le héros motive ses alliés à continuer le combat', NULL, 'Les alliés récupèrent 1d6+(marge de réussite/10) points d''endurance', NULL, 'Action bonus : ELO', '', NULL, NULL, 'R: /<br/>E: Le héros baisse sa garde et subit une attaque d''opportunité', 10, 1),
            ('Repositionnement', 'Le héros lutte pour déplacer son adversaire', NULL, 'La cible est déplacée de 1m + 1m par 10 points de marge de réussite.', NULL, 'Action de mouvement : DEX ou FOR', 'AGI ou VIG', NULL, NULL, 'R: /<br/>E: /', 11, 1),
            ('Tranche', 'Le héros saisit son arme à deux mains pour un violent coup horizontal', 'Arme polyvalente ou à deux mains', 'Touche toutes les cibles en face et à portée', NULL, 'Action complexe :<br/>Un seul jet d''Atq à -15', 'Chaque cible peut parer ou esquiver', NULL, NULL, 'R: Dégâts + 2<br/>E: /', 12, 1),
            ('Tranche-tendons', 'Le héros frappe la cible dans les articulations des jambes pour l''empêcher de bouger.', NULL, 'Déplacement de la cible limité à un mètre par round', NULL, 'Action simple :<br/>Jet d''attaque d''Atq à -25', 'Parade/Esquive à -10', NULL, NULL, 'R: dégâts + 3<br/>E: /', 13, 1)");

        // Section 2: Specialist — original entries from dump with section/category/tier/critique
        $this->addSql("INSERT INTO combat_art (name, description, conditions, effect, cost, assaillant_test, defender_test, category, tier, critique, order_index, section) VALUES
            ('Tir précis', 'L''arbalétrier prend son temps pour viser sa cible', NULL, 'Dégâts normaux', NULL, 'Action complexe :<br/>Tir à +15', '', 'Arbalétrier', 'Apprenti', 'R: /<br/>E: /', 1, 2),
            ('Tir déstabilisant', 'L''arbalétrier prépare un tir particulièrement puissant pour faire chuter sa cible', 'Jet rupture pour l''arme à +1', 'La cible est à terre', NULL, 'Action complexe :<br/>Tir classique', 'VIG pour ne pas tomber', 'Arbalétrier', 'Adepte', 'R: /<br/>E: /', 2, 2),
            ('Tir rapide', 'L''arbalétrier effectue un tir rapide à la hanche', NULL, 'Dégâts normaux', NULL, 'Action bonus :<br/>Tir à -15', '', 'Arbalétrier', 'Expert', 'R: /<br/>E: /', 3, 2),
            ('Tir pénétrant', 'L''arbalétrier tire sur deux cibles alignées et transperce la première pour atteindre la seconde', '2 cibles alignées', 'Dégâts normaux pour la première cible, -3 pour la deuxième', NULL, 'Action complexe :<br/>Tir classique', '', 'Arbalétrier', 'Expert', 'R: le carreau frappe une troisième cible si possible avec -6 dégâts.<br/>E: /', 4, 2),
            ('Volée de flèches', 'L''archer tire une flèche sur chacun des opposants qu''il a en ligne de mire (max 5)', NULL, 'Autant de jets que d''attaques réussies', NULL, 'Action complexe :<br/>Tir classique pour le premier, les tirs suivants subissent un malus de -10 par tir consécutif', '', 'Archer', 'Expert', 'R: /<br/>E: La corde de l''arc se brise (Rupture)', 3, 2),
            ('Frappe assassine', 'L''assassin frappe un point faible de l''adversaire', 'Attaque avec avantage', 'Degâts x1,5', NULL, 'Action simple :<br/>Atq classique', 'Parade/Esquive classique', 'Assassin', 'Apprenti', 'R: /<br/>E: /', 1, 2),
            ('Coup mortel', 'L''assassin élimine une cible incapable de se défendre', 'Cible vulnérable(aveuglée, immobilisée, inconscient, etc...)', 'Mort instantanée de la cible', NULL, 'Acton complexe :<br/>Jet d''Atq à -20', 'Jet de Vigueur', 'Assassin', 'Expert', 'R: /<br/>E: /', 2, 2),
            ('Frappe lourde', 'Le barbare envoie son adversaire au sol en le frappant avec un force surhumaine', 'FOR du barbare supérieure à celle de sa cible', 'Dégâts x1,5, cible mise au sol et envoyée à 1m + 1m par 10 points de marge de réussite.', NULL, 'Action complexe<br/>Atq à -10', 'jet d''AGI pour esquiver puis VIG pour résister à la mise au sol', 'Barbare', 'Apprenti', 'R: /<br/>E: /', 1, 2),
            ('Destruction', 'Le barbare tente de briser l''équipement de son adversaire avec son arme', 'Rupture du barbare supérieure à l''adversaire', 'L''équipement ciblé est endommagé (arme: Atq et Prd -15, Dgt -2; armure : PR -2)', NULL, 'Action simple :<br/>FOR', 'AGI pour l''armure ou DEX pour l''arme suivi d''un test de rupture', 'Barbare', 'Adepte', 'R: L''équipement ciblé est détruit<br/>E: /', 2, 2),
            ('Double attaque', 'Le héros frappe deux fois avec son arme dans un mouvement fluide', NULL, 'Autant de jets que d''attaques réussies', NULL, 'Action complexe :<br/>1er coup : Attaque classique<br/>2ème coup : Jet d''Atq à -10', 'Parade/Esquive classique pour chaque frappe', 'Épéiste', 'Apprenti', 'R: /<br/>E: /', 1, 2),
            ('Triple attaque', 'Le héros délivre un déluge de coup sur son adversaires et frappe trois fois', NULL, 'Autant de jets que d''attaques réussies', NULL, 'Action complexe :<br/>1er coup : Attaque classique, malus de -10 par attaque supplémentaire', 'Parade/Esquive classique pour chaque frappe', 'Épéiste', 'Expert', 'R: /<br/>E: /', 2, 2),
            ('Déplacement forcé', 'À l''aide de son arme, le faucheur force sa cible à se déplacer sous peine de subir une autre blessure', 'Après une attaque réussie', 'La cible est déplacée de 1m + 1m par 10 points de marge de réussite', NULL, 'Action de mouvement :<br/>DEX pour coincer l''adversaire puis FOR pour le tirer', 'AGI pour passer sous la lame puis VIG pour résister au déplacement', 'Faucheur', 'Apprenti', 'R: /<br/>E: /', 1, 2),
            ('Frappe dans le dos', 'Le faucheur utilise son arme pour frapper sa cible dans le dos, où l''armure est plus fine', NULL, 'Ignore 2 points de PR de l''armure', NULL, 'Action simple :<br/>Jet d''Atq à -10', 'Parade/Esquive classique', 'Faucheur', 'Adepte', 'R: /<br/>E: /', 2, 2),
            ('Frappe de la faucheuse', 'Le faucheur frappe deux fois en un seul et large mouvement', NULL, 'Autant de jets que d''attaques réussies', NULL, 'Action complexe :<br/>1er coup : Attaque classique<br/>2ème coup : Jet d''Atq à -10', 'Parade/Esquive classique pour chaque frappe', 'Faucheur', 'Expert', 'R: /<br/>E: /', 3, 2),
            ('Réception de charge', 'Le hallebardier se prépare à infliger une attaque d''opportunité à quiconque pénètre sa zone de contrôle', NULL, 'Le hallebardier peut porter une attaque d''opportunité (avec un bonus de 10 à l''Atq) supplémentaire sur un adversaire pénétrant sa zone de contrôle.', NULL, 'Action de mouvement :<br/>Aucune épreuve pour se préparer', '', 'Hallebardier', 'Novice', 'R: /<br/>E: /', 0, 2),
            ('Mise au sol', 'Le hallebardier profite d''une attaque réussie pour agripper son adversaire avec le croc de son fer et l''amener au sol', 'Après une attaque réussie', 'La cible est à terre', NULL, 'Action bonus :<br/>FOR', 'VIG pour ne pas tomber', 'Hallebardier', 'Apprenti', 'R: /<br/>E: /', 1, 2),
            ('Frappe de la hampe', 'Le hallebardier enchaîne après une attaque par un coup de la hampe', 'Après une attaque', '1d4 de dégâts contondants', NULL, 'Action bonus :<br/>Atq', 'Parade/Esquive classique', 'Hallebardier', 'Adepte', 'R: /<br/>E: /', 2, 2),
            ('Double estoc', 'Le lancier frappe deux fois de la pointe de sa lance', NULL, 'Autant de jets que d''attaques réussies', NULL, 'Action complexe :<br/>1er coup : Attaque classique<br/>2ème coup : Jet d''Atq à -10', 'Parade/Esquive classique pour chaque frappe', 'Lancier', 'Apprenti', 'R: /<br/>E: /', 1, 2),
            ('Triple estoc', 'Le lancier délivre un déluge d''estoc sur son adversaires et frappe trois fois', NULL, 'Autant de jets que d''attaques réussies', NULL, 'Action complexe :<br/>1er coup : Attaque classique, malus de -10 par attaque supplémentaire', 'Parade/Esquive classique pour chaque frappe', 'Lancier', 'Expert', 'R: /<br/>E: /', 2, 2),
            ('Coup étourdissant', 'Le moine frappe son adversaire au visage pour l''étourdir', NULL, 'La cible est étourdie', NULL, 'Action complexe :<br/>Jet d''Atq à -10', 'VIG pour résister', 'Moine', 'Apprenti', 'R: /<br/>E: /', 1, 2),
            ('Enchaînement', 'Le moine enchaîne les coups et frappe deux fois avec son bâton', NULL, 'Autant de jets que d''attaques réussies', NULL, 'Action complexe :<br/>1er coup : Attaque classique<br/>2ème coup : Jet d''Atq à -10', 'Parade/Esquive classique pour chaque frappe', 'Moine', 'Adepte', 'R: /<br/>E: /', 2, 2),
            ('Enchaînement supérieur', 'Le moine délivre un déluge de coups sur son adversaires et frappe trois fois avec son bâton', NULL, 'Autant de jets que d''attaques réussies', NULL, 'Action complexe :<br/>1er coup : Attaque classique, malus de -10 par attaque supplémentaire', 'Parade/Esquive classique pour chaque frappe', 'Moine', 'Expert', 'R: /<br/>E: /', 3, 2),
            ('Harcelement', 'Le tirailleur harcèle ses adversaires avec trois tirs consécutifs', NULL, 'Dégâts normaux', NULL, 'Action complexe :<br/>Tir classique pour le premier, les tirs suivants subissent un malus de -10 par tir consécutif', '', 'Tirailleur', 'Adepte', 'R: /<br/>E: /', 2, 2)");
    }

    public function down(Schema $schema): void
    {
        $this->addSql("DELETE FROM combat_art WHERE section IN (1, 2) AND category IS NULL AND section = 1");
        $this->addSql("DELETE FROM combat_art WHERE section = 2 AND critique IN ('R: /<br/>E: /', 'R: L''équipement ciblé est détruit<br/>E: /', 'R: le carreau frappe une troisième cible si possible avec -6 dégâts.<br/>E: /', 'R: /<br/>E: La corde de l''arc se brise (Rupture)')");
    }
}
